version: '3.8'

services:
  api:
    build:
      context: ./pz-cheeseria-rest-api
      dockerfile: Dockerfile
    ports:
      - "7281:80"
    networks:
      - my-network

  frontend:
    build:
      context: ./pz-cheeseria-web-app/pz-cheeseria-web-app/
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

